import type {
  ChangedFile,
  FindingFeedbackStatus,
  GithubCommentPreview,
  HumanReviewRequest,
  HumanReviewStatus,
  ReviewTaskDetail,
  RiskLevel,
  TimelineItem
} from "@/types";
import { riskText } from "@/utils/risk";

export const chunkAggregateRiskText = (risk?: RiskLevel | string) => riskText((risk || "info") as RiskLevel);

export const chunkReasonText = (reason: string) => {
  const labels: Record<string, string> = {
    sensitive_path: "敏感路径",
    large_pr: "大 PR",
    file_count: "文件数较多",
    line_count: "变更行数较多",
    security: "认证权限",
    config: "运行配置",
    build: "构建发布",
    database: "数据库变更",
    database_migration: "数据库迁移",
    security_sensitive: "认证权限",
    runtime_config: "运行配置",
    delivery_pipeline: "构建发布",
    multi_file: "多文件变更",
    large_churn: "变更规模较大",
    standard: "常规分片"
  };
  return labels[reason] ?? reason;
};

export const timelineLabelText = (label: string) => {
  if (label === "Task queued") {
    return "任务已入队";
  }
  if (label === "Review started") {
    return "开始审查";
  }
  if (label === "GitHub diff fetched") {
    return "已拉取 GitHub Diff";
  }
  if (label === "Code review generated" || label === "Code review generated by LLM") {
    return "LLM 已生成审查结果";
  }
  if (label === "Code review generated by rule fallback") {
    return "规则兜底已生成审查结果";
  }
  if (label.startsWith("Code review generated by rule fallback:")) {
    return `规则兜底已生成审查结果：${label.replace("Code review generated by rule fallback:", "").trim()}`;
  }
  if (label === "Review completed") {
    return "审查完成";
  }
  if (label === "Review failed") {
    return "审查失败";
  }
  if (label.startsWith("Review failed:")) {
    return `审查失败：${label.replace("Review failed:", "").trim()}`;
  }
  return label;
};

export const changeTypeText = (type: ChangedFile["changeType"] | string) => {
  const labels: Record<string, string> = {
    A: "新增",
    M: "修改",
    D: "删除",
    ADD: "新增",
    MODIFY: "修改",
    DELETE: "删除",
    RENAMED: "重命名"
  };
  return labels[type] ?? type;
};

export const consumeStatusText = (status: string) => {
  const labels: Record<string, string> = {
    confirmed: "已确认",
    failed: "消费失败",
    pending: "等待消费"
  };
  return labels[status] ?? status;
};

export const commentBlockReasonText = (reason?: string) => {
  const labels: Record<string, string> = {
    "Finding is missing file path and will be posted as a PR comment": "缺少文件路径，将作为 PR 总评评论回写。",
    "Finding is missing a valid line number and will be posted as a PR comment": "缺少有效行号，将作为 PR 总评评论回写。",
    "Finding file is not in the changed files list and will be posted as a PR comment": "该文件不在本次 PR 变更文件列表中，将作为 PR 总评评论回写。",
    "Deleted files will be posted as PR comments": "删除文件将作为 PR 总评评论回写。",
    "Finding marked as false positive and will not be published": "已标记为误报，不会回写。",
    "Finding marked as fixed and will not be published": "已标记为已修复，不会回写。",
    "Finding marked as ignored and will not be published": "已标记为忽略，不会回写。",
    "Finding is not actionable and will not be published": "该问题当前不可处理，不会回写。"
  };
  return reason ? labels[reason] ?? reason : "";
};

export const commentTargetText = (targetType: string) => {
  const labels: Record<string, string> = {
    line: "行评论",
    pull_request: "PR 评论"
  };
  return labels[targetType] ?? targetType;
};

export const commentPreviewKey = (item: GithubCommentPreview["items"][number]) =>
  item.findingId ?? `${item.targetType}-${item.file}-${item.publicationStatus ?? "draft"}`;

export const sourceText = (source?: string) => {
  const labels: Record<string, string> = {
    manual_input: "手动输入",
    github_pr_picker: "GitHub PR 选择",
    existing_reused: "复用已有任务"
  };
  return source ? labels[source] ?? source : "手动输入";
};

export const repositoryText = (owner?: string, repository?: string) => {
  if (!owner || !repository) {
    return "未配置";
  }
  return `${owner} / ${repository}`;
};

export const writebackCheckStatusText = (status: string) => {
  const labels: Record<string, string> = {
    ready: "配置匹配",
    repository_mismatch: "仓库不一致",
    repository_not_configured: "仓库未配置",
    token_missing: "Token 缺失",
    connection_failed: "连接异常"
  };
  return labels[status] ?? status;
};

export const humanReviewPublishBlockReasonText = (
  humanReviewRequired: boolean | undefined,
  humanReviewStatus: HumanReviewStatus | string,
  isHumanReviewPublishAllowed: boolean
) => {
  if (!humanReviewRequired || isHumanReviewPublishAllowed) {
    return "";
  }
  if (humanReviewStatus === "pending") {
    return "当前任务等待人工审查，完成通过或要求修改后才能回写 GitHub 评论。";
  }
  if (humanReviewStatus === "rejected") {
    return "当前任务已被人工拒绝，不能回写 GitHub 评论。";
  }
  return "当前任务需要人工审查确认后才能回写 GitHub 评论。";
};

export const humanReviewStatusText = (status: string) => {
  const labels: Record<string, string> = {
    not_required: "无需人工审查",
    pending: "待人工审查",
    approved: "人工通过",
    changes_requested: "要求修改",
    rejected: "已拒绝"
  };
  return labels[status] ?? status;
};

export const humanReviewStatusClass = (status: string) => {
  const classes: Record<string, string> = {
    not_required: "success",
    pending: "warning",
    approved: "success",
    changes_requested: "warning",
    rejected: "danger"
  };
  return classes[status] ?? "pending";
};

export const humanReviewActionText = (action: HumanReviewRequest["action"]) => {
  const labels: Record<HumanReviewRequest["action"], string> = {
    approve: "通过审查",
    changes_requested: "要求修改",
    reject: "拒绝"
  };
  return labels[action];
};

export const findingFeedbackStatusText = (status?: FindingFeedbackStatus | string) => {
  const labels: Record<string, string> = {
    unreviewed: "未判定",
    valid: "有效",
    false_positive: "误报",
    fixed: "已修复",
    ignored: "忽略"
  };
  return status ? labels[String(status).toLowerCase()] ?? String(status) : labels.unreviewed;
};

export const findingFeedbackStatusClass = (status?: FindingFeedbackStatus | string) => {
  const classes: Record<string, string> = {
    unreviewed: "pending",
    valid: "success",
    false_positive: "warning",
    fixed: "success",
    ignored: "pending"
  };
  return status ? classes[String(status).toLowerCase()] ?? "pending" : "pending";
};

export const findingFeedbackPromptTitle = (status: FindingFeedbackStatus) => {
  const labels: Record<FindingFeedbackStatus, string> = {
    unreviewed: "重置判定",
    valid: "标记为有效",
    false_positive: "标记为误报",
    fixed: "标记为已修复",
    ignored: "标记为忽略"
  };
  return labels[status];
};

export const publishStatusText = (status: string) => {
  const labels: Record<string, string> = {
    published: "已发布",
    failed: "失败",
    skipped: "跳过",
    already_published: "已发布，已跳过",
    downgraded_to_pr_comment: "已降级为 PR 评论"
  };
  return labels[status] ?? status;
};

export const publicationBatchStatusText = (status: string) => {
  const labels: Record<string, string> = {
    completed: "完成",
    partial_failed: "部分失败",
    failed: "失败",
    skipped: "全部跳过",
    empty: "无审查发现"
  };
  return labels[status] ?? status;
};

export const publicationBatchStatusClass = (status: string) => {
  const classes: Record<string, string> = {
    completed: "success",
    partial_failed: "warning",
    failed: "danger",
    skipped: "warning",
    empty: "pending"
  };
  return classes[status] ?? "pending";
};

export const publicationItemStatusClass = (status: string) => {
  const classes: Record<string, string> = {
    published: "success",
    downgraded_to_pr_comment: "success",
    already_published: "skipped",
    skipped: "skipped",
    failed: "failed"
  };
  return classes[status] ?? "skipped";
};

export const publicationMessageText = (message: string | undefined, status: string) => {
  const labels: Record<string, string> = {
    "GitHub comment published": "GitHub 评论已发布。",
    "GitHub comment already published": "该审查发现此前已经发布，本次已跳过。",
    "GitHub line comment could not be resolved; published as PR comment": "GitHub 行评论定位失败，已降级为 PR 总评评论。"
  };
  if (message && labels[message]) {
    return labels[message];
  }
  if (message) {
    return message;
  }
  const fallbackLabels: Record<string, string> = {
    published: "GitHub 评论已发布。",
    downgraded_to_pr_comment: "GitHub 行评论定位失败，已降级为 PR 总评评论。",
    already_published: "该审查发现此前已经发布，本次已跳过。",
    skipped: "本次未回写该审查发现。",
    failed: "GitHub 评论回写失败。"
  };
  return fallbackLabels[status] ?? status;
};

export const refreshStatusText = ({
  currentPollIntervalSeconds,
  lastRefreshedAt,
  pollErrorMessage,
  pollFailureCount,
  selectedTaskStatus,
  shouldPollTask,
  silentRefreshing,
  maxPollFailures
}: {
  currentPollIntervalSeconds: number;
  lastRefreshedAt: string;
  pollErrorMessage: string;
  pollFailureCount: number;
  selectedTaskStatus?: string;
  shouldPollTask: boolean;
  silentRefreshing: boolean;
  maxPollFailures: number;
}) => {
  if (shouldPollTask) {
    if (silentRefreshing) {
      return "正在自动刷新任务状态...";
    }
    if (pollErrorMessage) {
      if (pollFailureCount >= maxPollFailures) {
        return "自动刷新已暂停，请手动刷新";
      }
      return `自动刷新上次失败，将在 ${currentPollIntervalSeconds} 秒后重试`;
    }
    return `自动刷新中，每 ${currentPollIntervalSeconds} 秒更新一次`;
  }
  if (selectedTaskStatus === "failed") {
    return lastRefreshedAt ? `任务失败，最后更新 ${lastRefreshedAt}` : "任务失败";
  }
  return lastRefreshedAt ? `已完成，最后更新 ${lastRefreshedAt}` : "已完成";
};

export const statusReasonText = (failureReason: string, timeline: TimelineItem[]) => {
  if (failureReason) {
    return failureReason;
  }
  const reasonLabel = timeline
    .map((item) => item.label)
    .find((label) => label.startsWith("Code review generated by rule fallback:") || label.startsWith("Review failed:"));
  if (!reasonLabel) {
    return "";
  }
  return reasonLabel
    .replace("Code review generated by rule fallback:", "")
    .replace("Review failed:", "")
    .trim();
};

export const llmModelText = (llm: ReviewTaskDetail["llm"]) => {
  if (!llm.model && !llm.provider) {
    return "-";
  }
  return [llm.provider, llm.model].filter(Boolean).join(" / ");
};

export const llmDurationText = (llm: ReviewTaskDetail["llm"]) => {
  const durationMs = llm.durationMs;
  if (typeof durationMs === "number" && Number.isFinite(durationMs)) {
    return `${durationMs} ms`;
  }
  return llm.duration ?? "-";
};

export const llmTokenUsageText = (llm?: ReviewTaskDetail["llm"]) => {
  if (!llm || !llm.totalTokens) {
    return "未记录";
  }
  return `${llm.totalTokens} total / ${llm.promptTokens ?? 0} prompt / ${llm.completionTokens ?? 0} completion`;
};

export const llmCostText = (llm?: ReviewTaskDetail["llm"]) => {
  const cost = llm?.estimatedCost;
  return cost ? `$${cost}` : "未配置单价";
};

export const llmParseStatusText = (llm?: ReviewTaskDetail["llm"]) => {
  const labels: Record<string, string> = {
    parsed: "解析成功",
    fallback: "规则兜底",
    failed: "解析失败",
    pending: "等待执行"
  };
  const status = llm?.parseStatus || (llm?.status === "fallback" ? "fallback" : "pending");
  return labels[status] ?? status;
};

export const llmParseStatusClass = (llm?: ReviewTaskDetail["llm"]) => {
  const status = llm?.parseStatus || llm?.status;
  if (status === "parsed" || status === "completed") {
    return "success";
  }
  if (status === "fallback") {
    return "warning";
  }
  if (status === "failed") {
    return "danger";
  }
  return "pending";
};
