create table if not exists data_retention_cleanup_audit (
    id bigint primary key auto_increment,
    mode varchar(16) not null,
    status varchar(32) not null,
    retention_days int not null,
    max_tasks int not null,
    backup_reference varchar(128) null,
    cutoff_time datetime not null,
    candidate_tasks bigint not null default 0,
    selected_tasks int not null default 0,
    deleted_batch_items int not null default 0,
    deleted_publications int not null default 0,
    deleted_batches int not null default 0,
    deleted_changed_files int not null default 0,
    deleted_timelines int not null default 0,
    deleted_findings int not null default 0,
    deleted_tasks int not null default 0,
    failure_reason varchar(64) null,
    failure_message varchar(512) null,
    created_at datetime not null,
    completed_at datetime null,
    updated_at datetime not null,
    key idx_data_retention_cleanup_audit_created_at (created_at),
    key idx_data_retention_cleanup_audit_status (status, mode, created_at),
    key idx_data_retention_cleanup_audit_backup_reference (backup_reference)
);
