create table if not exists review_task_archive_summary (
    id bigint auto_increment primary key,
    task_id bigint not null,
    cleanup_batch_id bigint not null,
    organization varchar(128) not null,
    repository varchar(128) not null,
    pr_number int not null,
    title varchar(512) not null,
    commit_sha varchar(64) not null,
    branch_name varchar(128) not null,
    status varchar(32) not null,
    risk_level varchar(32) not null,
    source varchar(32),
    trigger_source varchar(32),
    created_at datetime not null,
    finished_at datetime,
    duration_seconds int not null default 0,
    finding_count int not null default 0,
    changed_file_count int not null default 0,
    timeline_count int not null default 0,
    publication_count int not null default 0,
    backup_reference varchar(128) not null,
    archived_at datetime not null default current_timestamp,
    unique key uk_review_task_archive_summary_task (task_id),
    key idx_review_task_archive_summary_repo_created (organization, repository, created_at),
    key idx_review_task_archive_summary_created (created_at),
    key idx_review_task_archive_summary_batch (cleanup_batch_id)
);
