package com.repoguard.agent.worker;

import com.repoguard.agent.entity.ReviewTask;
import com.repoguard.agent.review.LlmParseStatus;
import com.repoguard.agent.review.LlmStatus;
import com.repoguard.agent.review.ReviewResult;
import com.repoguard.agent.timeline.ReviewTimelineAppender;
import java.time.LocalDateTime;
import org.springframework.stereotype.Component;

@Component
class ReviewExecutionTimelineRecorder {

    private final ReviewTimelineAppender timelineAppender;

    ReviewExecutionTimelineRecorder(ReviewTimelineAppender timelineAppender) {
        this.timelineAppender = timelineAppender;
    }

    void reviewStarted(ReviewTask task, LocalDateTime eventTime) {
        timelineAppender.append(task.getId(), "Review started", eventTime, "CURRENT", 2);
    }

    void diffFetched(ReviewTask task, LocalDateTime eventTime) {
        timelineAppender.append(task.getId(), "GitHub diff fetched", eventTime, "DONE", 3);
    }

    void reviewGenerated(ReviewTask task, ReviewResult reviewResult, LocalDateTime eventTime) {
        timelineAppender.append(task.getId(), reviewGeneratedLabel(reviewResult), eventTime, "DONE", 4);
    }

    void reviewTerminal(ReviewTask task, boolean humanReviewRequired, LocalDateTime eventTime) {
        timelineAppender.append(
            task.getId(),
            humanReviewRequired ? "Human review required" : "Review completed",
            eventTime,
            humanReviewRequired ? "CURRENT" : "DONE",
            5
        );
    }

    void reviewFailed(ReviewTask task, RuntimeException ex, LocalDateTime eventTime) {
        timelineAppender.append(task.getId(), failureLabel(ex), eventTime, "FAILED", 5);
    }

    private String reviewGeneratedLabel(ReviewResult reviewResult) {
        if (LlmParseStatus.PARTIAL_FALLBACK.is(reviewResult.llmParseStatus())) {
            return "Code review generated with partial rule fallback";
        }
        if (LlmStatus.FALLBACK != LlmStatus.from(reviewResult.llmStatus())) {
            return "Code review generated";
        }
        String detail = reviewResult.statusDetail();
        if (detail == null || detail.isBlank()) {
            return "Code review generated by rule fallback";
        }
        return truncateLabel("Code review generated by rule fallback: " + detail.replaceAll("\\s+", " ").trim());
    }

    private String failureLabel(RuntimeException ex) {
        String message = ex.getMessage();
        if (message == null || message.isBlank()) {
            return "Review failed";
        }
        String normalized = message.replaceAll("\\s+", " ").trim();
        return truncateLabel("Review failed: " + normalized);
    }

    private String truncateLabel(String label) {
        return label.length() > 120 ? label.substring(0, 117) + "..." : label;
    }
}
