package com.repoguard.agent.worker;

import com.repoguard.agent.config.CacheEvictionService;
import com.repoguard.agent.entity.ReviewTask;
import com.repoguard.agent.github.GithubPullRequestDiff;
import com.repoguard.agent.mapper.ReviewTaskMapper;
import com.repoguard.agent.review.LlmStatus;
import com.repoguard.agent.review.ReviewResult;
import java.time.LocalDateTime;
import org.springframework.stereotype.Component;

@Component
class ReviewExecutionResultWriter {

    private final ReviewTaskMapper reviewTaskMapper;
    private final ReviewTaskClaimService claimService;
    private final ReviewTaskCompletionApplier completionApplier;
    private final ChangedFileReplacementService changedFileReplacementService;
    private final ReviewFindingReplacementService findingReplacementService;
    private final ReviewTimelineAppender timelineAppender;
    private final ReviewExecutionMetricsRecorder metricsRecorder;
    private final CacheEvictionService cacheEvictionService;

    ReviewExecutionResultWriter(
        ReviewTaskMapper reviewTaskMapper,
        ReviewTaskClaimService claimService,
        ReviewTaskCompletionApplier completionApplier,
        ChangedFileReplacementService changedFileReplacementService,
        ReviewFindingReplacementService findingReplacementService,
        ReviewTimelineAppender timelineAppender,
        ReviewExecutionMetricsRecorder metricsRecorder,
        CacheEvictionService cacheEvictionService
    ) {
        this.reviewTaskMapper = reviewTaskMapper;
        this.claimService = claimService;
        this.completionApplier = completionApplier;
        this.changedFileReplacementService = changedFileReplacementService;
        this.findingReplacementService = findingReplacementService;
        this.timelineAppender = timelineAppender;
        this.metricsRecorder = metricsRecorder;
        this.cacheEvictionService = cacheEvictionService;
    }

    WriteResult applyCompleted(
        ReviewTask task,
        GithubPullRequestDiff diff,
        ReviewResult reviewResult,
        LocalDateTime startedAt,
        String claimId
    ) {
        LocalDateTime finishedAt = LocalDateTime.now();
        boolean humanReviewRequired = completionApplier.applyCompleted(task, reviewResult, startedAt, finishedAt);
        claimService.ensureClaimOwnedAndFenceTerminalStatus(task, claimId);
        task.setReviewClaimedAt(null);
        task.setReviewClaimedBy(null);
        reviewTaskMapper.updateById(task);
        changedFileReplacementService.replace(task.getId(), diff);
        timelineAppender.append(task.getId(), "GitHub diff fetched", finishedAt, "DONE", 3);
        int findingCount = findingReplacementService.replace(task.getId(), reviewResult);
        timelineAppender.append(task.getId(), reviewGeneratedLabel(reviewResult), finishedAt, "DONE", 4);
        timelineAppender.append(
            task.getId(),
            humanReviewRequired ? "Human review required" : "Review completed",
            finishedAt,
            humanReviewRequired ? "CURRENT" : "DONE",
            5
        );
        metricsRecorder.recordCompleted(reviewResult, startedAt, finishedAt);
        evictDashboardOverview();
        return new WriteResult(findingCount, humanReviewRequired);
    }

    private void evictDashboardOverview() {
        if (cacheEvictionService != null) {
            cacheEvictionService.evictDashboardOverview();
        }
    }

    private String reviewGeneratedLabel(ReviewResult reviewResult) {
        if ("partial_fallback".equalsIgnoreCase(reviewResult.llmParseStatus())) {
            return "Code review generated with partial rule fallback";
        }
        if (LlmStatus.FALLBACK != LlmStatus.from(reviewResult.llmStatus())) {
            return "Code review generated";
        }
        String detail = reviewResult.statusDetail();
        if (detail == null || detail.isBlank()) {
            return "Code review generated by rule fallback";
        }
        return truncateLabel("Code review generated by rule fallback: " + detail.replaceAll("\\s+", " ").trim());
    }

    private String truncateLabel(String label) {
        return label.length() > 120 ? label.substring(0, 117) + "..." : label;
    }

    record WriteResult(int findingCount, boolean humanReviewRequired) {
    }
}
