package com.repoguard.agent.worker;

import com.repoguard.agent.review.LlmParseStatus;
import com.repoguard.agent.review.LlmStatus;
import com.repoguard.agent.review.ReviewResult;
import org.springframework.stereotype.Component;

@Component
class ReviewExecutionTimelineLabelFormatter {

    String reviewGenerated(ReviewResult reviewResult) {
        if (LlmParseStatus.PARTIAL_FALLBACK.is(reviewResult.llmParseStatus())) {
            return "Code review generated with partial rule fallback";
        }
        if (LlmStatus.FALLBACK != LlmStatus.from(reviewResult.llmStatus())) {
            return "Code review generated";
        }
        String detail = reviewResult.statusDetail();
        if (detail == null || detail.isBlank()) {
            return "Code review generated by rule fallback";
        }
        return truncateLabel("Code review generated by rule fallback: " + normalize(detail));
    }

    String reviewTerminal(boolean humanReviewRequired) {
        return humanReviewRequired ? "Human review required" : "Review completed";
    }

    String reviewFailed(RuntimeException ex) {
        String message = ex.getMessage();
        if (message == null || message.isBlank()) {
            return "Review failed";
        }
        return truncateLabel("Review failed: " + normalize(message));
    }

    private String normalize(String value) {
        return value.replaceAll("\\s+", " ").trim();
    }

    private String truncateLabel(String label) {
        return label.length() > 120 ? label.substring(0, 117) + "..." : label;
    }
}
