package com.repoguard.agent.worker;

import static org.assertj.core.api.Assertions.assertThat;

import com.repoguard.agent.review.ReviewResult;
import java.util.List;
import org.junit.jupiter.api.Test;

class ReviewExecutionTimelineLabelFormatterTest {

    private final ReviewExecutionTimelineLabelFormatter formatter = new ReviewExecutionTimelineLabelFormatter();

    @Test
    void formatsGeneratedReviewLabels() {
        assertThat(formatter.reviewGenerated(ReviewResult.completed("LOW", List.of())))
            .isEqualTo("Code review generated");
    }

    @Test
    void formatsFallbackAndPartialFallbackLabels() {
        ReviewResult fallback = ReviewResult.fallback("LOW", "llm timeout", List.of());
        ReviewResult partialFallback = ReviewResult.completed(
            "LOW",
            List.of(),
            "dashscope",
            "mimo-v2.5-pro",
            10354,
            "partial_fallback",
            "chunked=true; failedChunks=2",
            null,
            null,
            null,
            null
        );

        assertThat(formatter.reviewGenerated(fallback))
            .isEqualTo("Code review generated by rule fallback: llm timeout");
        assertThat(formatter.reviewGenerated(partialFallback))
            .isEqualTo("Code review generated with partial rule fallback");
    }

    @Test
    void normalizesAndTruncatesFailureLabel() {
        String longMessage = "github\nunavailable " + "x".repeat(140);

        String label = formatter.reviewFailed(new IllegalStateException(longMessage));

        assertThat(label).startsWith("Review failed: github unavailable ");
        assertThat(label).hasSize(120);
        assertThat(label).endsWith("...");
    }

    @Test
    void formatsTerminalLabels() {
        assertThat(formatter.reviewTerminal(false)).isEqualTo("Review completed");
        assertThat(formatter.reviewTerminal(true)).isEqualTo("Human review required");
        assertThat(formatter.reviewFailed(new IllegalStateException())).isEqualTo("Review failed");
    }
}
